version: '3.8'

services:
  api-gateway:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      # Add your microservice URLs
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - USERS_SERVICE_URL=${USERS_SERVICE_URL}
      - ORDERS_SERVICE_URL=${ORDERS_SERVICE_URL}
      - PRODUCTS_SERVICE_URL=${PRODUCTS_SERVICE_URL}
      - PAYMENTS_SERVICE_URL=${PAYMENTS_SERVICE_URL}
      - NOTIFICATIONS_SERVICE_URL=${NOTIFICATIONS_SERVICE_URL}
      - ANALYTICS_SERVICE_URL=${ANALYTICS_SERVICE_URL}
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - gateway-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - gateway-network
    command: redis-server --appendonly yes

volumes:
  redis-data:

networks:
  gateway-network:
    driver: bridge